locale: "en-US"
sql:
  enabled: false
  ip: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"
  max-pool-size: 100
broker:
  disable-commands: false
  charge-fees-on-sale: false
  flat-fee: 10.50
  percent-fee: 0.20
  names:
    simple: "&8&lStock Broker"
cache:
  expire-minutes: 5
unknown-data: "N/A"
block-transactions-when-market-closed: true
transaction-cooldown-seconds: 2
minutes-between-sale: 5
minimum-price: 5.0
price-multiplier: 20
allowed-currencies:
  - "USD"
  - "CAD"
allowed-exchanges: []