storage:
  mysql:
    enabled: false
    ip: "localhost"
    port: 3306
    database: "database"
    username: "username"
    password: "password"
    max-pool-size: 100
brokers:
  names:
    simple: "&8&lStock Broker"
  settings:
    disable-commands: false
inventories:
    historical:
      data:
        material: "ENCHANTED_BOOK"
        amount: 1
        durability: 0
        name: "&6&l<date>"
        lore:
          - "&6Day Open:"
          - "&e<day-open> <market-currency>"
          - "&6Day Close:"
          - "&e<day-close> <market-currency>"
          - "&6Volume:"
          - "&e<volume>"
          - "&6Day High:"
          - "&e<day-high> <market-currency>"
          - "&6Day Low:"
          - "&e<day-low> <market-currency>"
      no-data:
        material: "BARRIER"
        amount: 1
        durability: 0
        name: "&6&lNo Historical Data"
        lore:
          - "&eNo Data Available"
      slots:
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 30
        - 31
        - 32
settings:
  locale: "en-US"
  broker:
    charge-fees-on-sale: false
    flat-fee: 10.50
    percent-fee: 0.20
  cache:
    expire-minutes: 5
  unknown-data: "N/A"
  block-transactions-when-market-closed: true
  transaction-cooldown-seconds: 2
  minutes-between-sale: 5
  minimum-price: 5.0
  price-multiplier: 20
  allowed-currencies:
    - "USD"
    - "CAD"
  allowed-exchanges: []