name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'java'
      - name: Test with mvn
        run: mvn -B compile test --file pom.xml
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      - name: Run codacy-coverage-reporter
        if: github.ref == 'refs/heads/main'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./target/site/jacoco/jacoco.xml